// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.3
// source: sub.proto

package mygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number1 int64 `protobuf:"varint,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2 int64 `protobuf:"varint,2,opt,name=number2,proto3" json:"number2,omitempty"`
}

func (x *SubReq) Reset() {
	*x = SubReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubReq) ProtoMessage() {}

func (x *SubReq) ProtoReflect() protoreflect.Message {
	mi := &file_sub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubReq.ProtoReflect.Descriptor instead.
func (*SubReq) Descriptor() ([]byte, []int) {
	return file_sub_proto_rawDescGZIP(), []int{0}
}

func (x *SubReq) GetNumber1() int64 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *SubReq) GetNumber2() int64 {
	if x != nil {
		return x.Number2
	}
	return 0
}

type SubResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *SubResp) Reset() {
	*x = SubResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResp) ProtoMessage() {}

func (x *SubResp) ProtoReflect() protoreflect.Message {
	mi := &file_sub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResp.ProtoReflect.Descriptor instead.
func (*SubResp) Descriptor() ([]byte, []int) {
	return file_sub_proto_rawDescGZIP(), []int{1}
}

func (x *SubResp) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_sub_proto protoreflect.FileDescriptor

var file_sub_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x79, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x3c, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x32, 0x22, 0x21, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x32, 0x34, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x12, 0x0e, 0x2e, 0x6d, 0x79, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x79, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x6d,
	0x79, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sub_proto_rawDescOnce sync.Once
	file_sub_proto_rawDescData = file_sub_proto_rawDesc
)

func file_sub_proto_rawDescGZIP() []byte {
	file_sub_proto_rawDescOnce.Do(func() {
		file_sub_proto_rawDescData = protoimpl.X.CompressGZIP(file_sub_proto_rawDescData)
	})
	return file_sub_proto_rawDescData
}

var file_sub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sub_proto_goTypes = []interface{}{
	(*SubReq)(nil),  // 0: mygrpc.SubReq
	(*SubResp)(nil), // 1: mygrpc.SubResp
}
var file_sub_proto_depIdxs = []int32{
	0, // 0: mygrpc.SubService.sub:input_type -> mygrpc.SubReq
	1, // 1: mygrpc.SubService.sub:output_type -> mygrpc.SubResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sub_proto_init() }
func file_sub_proto_init() {
	if File_sub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sub_proto_goTypes,
		DependencyIndexes: file_sub_proto_depIdxs,
		MessageInfos:      file_sub_proto_msgTypes,
	}.Build()
	File_sub_proto = out.File
	file_sub_proto_rawDesc = nil
	file_sub_proto_goTypes = nil
	file_sub_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SubServiceClient is the client API for SubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubServiceClient interface {
	Sub(ctx context.Context, in *SubReq, opts ...grpc.CallOption) (*SubResp, error)
}

type subServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubServiceClient(cc grpc.ClientConnInterface) SubServiceClient {
	return &subServiceClient{cc}
}

func (c *subServiceClient) Sub(ctx context.Context, in *SubReq, opts ...grpc.CallOption) (*SubResp, error) {
	out := new(SubResp)
	err := c.cc.Invoke(ctx, "/mygrpc.SubService/sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubServiceServer is the server API for SubService service.
type SubServiceServer interface {
	Sub(context.Context, *SubReq) (*SubResp, error)
}

// UnimplementedSubServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSubServiceServer struct {
}

func (*UnimplementedSubServiceServer) Sub(context.Context, *SubReq) (*SubResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}

func RegisterSubServiceServer(s *grpc.Server, srv SubServiceServer) {
	s.RegisterService(&_SubService_serviceDesc, srv)
}

func _SubService_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubServiceServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mygrpc.SubService/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubServiceServer).Sub(ctx, req.(*SubReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mygrpc.SubService",
	HandlerType: (*SubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sub",
			Handler:    _SubService_Sub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sub.proto",
}
